### ISSUE TITLE
Event APIs

### ISSUE THREAD

**Issue by maddie927** [truqu/purescript-workers#1]
Thanks for starting this project!  I was attempting to implement [this service worker example](https://serviceworke.rs/strategy-cache-and-update_service-worker_doc.html) in PS and had to add some FFI for the event bits.  I'm not too familiar with the whole Service Worker API yet, so I'm not sure where these things belong, but I don't mind PR'ing them in if they go here somewhere.

Here's my PS file:

```purescript
module ServiceWorker where
  
import Prelude

import Cache (CACHE, Cache, addAll, match, openCache, put)
import Control.Monad.Aff (Aff)
import Control.Monad.Eff (Eff)
import Control.Monad.Eff.Class (liftEff)
import Control.Monad.Eff.Console (CONSOLE, log)
import Control.Monad.Eff.Exception (error)
import Control.Monad.Eff.Uncurried (EffFn2, runEffFn2)
import Control.Monad.Error.Class (throwError)
import Control.Promise (Promise, fromAff)
import Data.Foreign (isNull, toForeign, typeOf, unsafeFromForeign)
import Data.String (null)
import Fetch (FETCH, RequestInfo, Response, fetch)
import GlobalScope.Service (caches)
import Workers (WORKER)

type WorkerEffects e =
  ( worker :: WORKER
  | e )

type CacheEffects e = WorkerEffects
  ( cache :: CACHE
  | e )

type FetchEffects e =
  ( fetch :: FETCH
  | e )
  
appResources :: Array String
appResources =
  [ "./"
  , "./dist/app.js"
  ]

prepareServiceWorker :: forall e
   . Eff
      (WorkerEffects
        (CacheEffects
          (FetchEffects ( console :: CONSOLE | e ))))
      Unit
prepareServiceWorker = do
  addEventListener "install" \evt -> do
    log "The service worker is being installed."
    waitUntil evt =<< fromAff precache
  addEventListener "fetch" \evt -> do
    log "The service worker is serving the asset."
    respondWith evt =<< fromAff (fromCache (request evt))
    waitUntil evt =<< fromAff (update (request evt))

appCache :: forall e. Aff (CacheEffects e) Cache
appCache = do
  cacheStorage <- liftEff caches
  openCache cacheStorage "app"

precache :: forall e. Aff (CacheEffects e) Unit
precache = do
  cache <- appCache
  addAll cache appResources

fromCache :: forall e. RequestInfo -> Aff (CacheEffects e)
      Response
fromCache request = do
  cache <- appCache
  m <- match cache request
  if isEmpty m
    then throwError $ error "no-match"
    else pure m
  where
    isEmpty m =
      let
        mf = toForeign m
      in
        isNull mf ||
          (typeOf mf == "string" &&
            null (unsafeFromForeign mf :: String))

update :: forall e. RequestInfo -> Aff (CacheEffects (FetchEffects e)) Unit
update request = do
  response <- fetch request
  cache <- appCache
  put cache request response


-- | FFI Helpers

foreign import data Event :: Type

type EventHandler e = forall a. Event -> Eff e Unit

foreign import request :: Event -> RequestInfo

addEventListener :: forall e
   . String
  -> EventHandler e
  -> Eff (WorkerEffects e) Unit
addEventListener = runEffFn2 addEventListener_

foreign import addEventListener_ :: forall e
   . EffFn2 (WorkerEffects e) String (EventHandler e) Unit

waitUntil :: forall e a
   . Event
  -> (Promise a)
  -> Eff (WorkerEffects e) Unit
waitUntil = runEffFn2 waitUntil_

foreign import waitUntil_ :: forall e a
   . EffFn2 (WorkerEffects e) Event (Promise a) Unit

respondWith :: forall e a
   . Event
  -> (Promise a)
  -> Eff (WorkerEffects e) Unit
respondWith = runEffFn2 waitUntil_

foreign import respondWith_ :: forall e a
   . EffFn2 (WorkerEffects e) Event (Promise a) Unit
```

And my FFI file:

```javascript
"use strict";

exports.addEventListener_ = function(event, handler) {
  self.addEventListener(event, handler);
}

exports.waitUntil_ = function(evt, promise) {
  evt.waitUntil(promise);
}

exports.respondWith_ = function(evt, promise) {
  evt.respondWith(promise);
}
```

**Comment by maddie927** [comment]
Also in a complete solution I'd change some of these to hide the promises for the normal PS api.

**Comment by KtorZ** [comment]
Hey!

Thanks for your question (it makes me wake-up a bit and move my butt :)). I have planned to translate some JavaScript examples for a while but never really ~got~ took the time to do so. Though, you can now find a 100% PureScript implementation of the `service-worker.js` [here](https://github.com/truqu/purescript-workers/blob/master/examples/cache-and-update/service)

I didn't wanted to release those things yet as they haven't gone through a thorough testing but well, if I want people to also help, they need to have access to the whole API ^.^ ...
So, I've released the experimental API for the `fetch` API that you can find here:

https://pursuit.purescript.org/packages/purescript-workers/2.1.0/docs/Fetch

It's big but it's merely loads of accessors, and the might `fetch` function. This was needed to in order to complete the API for the service worker GlobalScope (which by the by, contains the hooks to register listeners to the events you are looking for). 

In the 2.1.0, I've also updated the signature to the `onFetch` to allow 2 kinds of effects to be passed:

- An effect for handling the immediate response to the request (correspond to the `respondWith` operation)
- An effect to perform background job once the response has been sent (correspond to the `waitUntil` operation)

They should be sufficient to enable any kind of actions required as response to the `fetch` event. So, let me walk you through this example.


## Cache and Update

The 'main' JavaScript program is simply defining a top-level var for the cache's name as well as registering functions to respond to the `install` and `fetch` events.

#### Main Structure

```js
var CACHE = 'cache-and-update';

self.addEventListener('install', function(evt) {
  console.log('The service worker is being installed.');
  evt.waitUntil(precache());
});

self.addEventListener('fetch', function(evt) {
  console.log('The service worker is serving the asset.');
  evt.respondWith(fromCache(evt.request));
  evt.waitUntil(update(evt.request));
});
```

In PureScript, it is also quite straighforward, and we can simply use the event listeners `onInstall` and `onFetch` which expects some asynchronous effects `Aff ( | e)` as parameters as we will see in a bit:

```purs
import GlobalScope.Service (onInstall, onFetch)
import Workers             (WORKER)

cacheName :: String
cacheName =
  "cache-and-update"

main :: forall e.  Eff (worker :: WORKER | e) Unit
main =
  onInstall preCache *> onFetch fromCache update
```

#### Pre-Cache

Then, we have this `preCache` function which retrieves a cache from the store and add the file we want to actually cache.

```js
function precache() {
  return caches.open(CACHE).then(function (cache) {
    return cache.addAll([
      './controlled.html',
      './asset'
    ]);
  });
}
```

In PureScript, operation on caches are defined in the `Cache` module, but the cache store belongs to the `GlobalScope/Service` module as it is a global variable accessible within the service worker scope.
Note that the log from above has been move here for simplicity. 

``` purs
import Cache                as Cache
import Cache               (CACHE)
import GlobalScope.Service (caches)
import Workers             (WORKER)

preCache :: forall e.  Aff (console :: CONSOLE, cache :: CACHE, worker :: WORKER | e) Unit
preCache = do
  log "The service worker is being installed"
  storage <- liftEff caches
  cache   <- Cache.openCache storage cacheName
  Cache.addAll cache
    [ "./controlled.html"
    , "./asset"
    ]
```

#### FromCache

Then, we have the action in which handle the immediate response to a request. 

```js
function fromCache(request) {
  return caches.open(CACHE).then(function (cache) {
    return cache.match(request).then(function (matching) {
      return matching || Promise.reject('no-match');
    });
  });
}
```

And in PureScript. Note that, the response type for this action is a `Maybe Response`. In case of `Nothing`, the FFI code will automatically fetch the given resource. In case of `Just response`, no request will be performed and the cached response will be returned right away. Also, note that this callback function takes one argument which is the actual `Request` responsible for triggering this `fetch` event.

```purs
import Cache                as Cache
import Cache               (CACHE)
import Fetch               (Request, Response, requestURL)
import GlobalScope.Service (caches)
import Workers             (WORKER)

fromCache :: forall e. Request -> Aff (worker :: WORKER, cache :: CACHE, console :: CONSOLE | e) (Maybe Response)
fromCache req = do
  log "The service worker is serving the asset."
  storage <- liftEff caches
  cache   <- Cache.openCache storage cacheName
  Cache.match cache (requestURL req)
```

#### Update

And finally, the update function passed to the `waitUntil` handler:

```js
function update(request) {
  return caches.open(CACHE).then(function (cache) {
    return fetch(request).then(function (response) {
      return cache.put(request, response);
    });
  });
}
```

And in PureScript

```purs
import Cache                as Cache
import Cache               (CACHE)
import Fetch               (fetch, requestURL)
import GlobalScope.Service (caches)
import Workers             (WORKER)

update :: forall e. Request -> Aff (worker :: WORKER, cache :: CACHE, console :: CONSOLE | e) Unit
update req = do
  storage <- liftEff caches
  cache   <- Cache.openCache storage cacheName
  res     <- fetch req
  Cache.put cache (requestURL req) res
```

The answer is rather long but I hope it helps. I've added some instruction on how to run this example from the source. For now, I've only translated the `service-worker.js` code to replace the pure js implementation from the Mozilla cookbook. It does work fine for this example and ideally, I would like to translate more examples as well as the JavaScript code registering the webworkers in order to have a 100% PureScript implementation. 

Help is truly welcome on that, as well as any feedback on the API or bugs you may find.

**Comment by maddie927** [comment]
This is amazing!  Thanks for the update and these detailed examples!
